### ISSUE TITLE
🔖 1.0.0 | Milestone

### ISSUE THREAD

**Issue by devcsrj** [devcsrj/kongresmo#2]
The first iteration of the project is purely a client-side only application. This means that all data will directly come from the [Philippine Senate](https://www.senate.gov.ph/lis/leg_sys.aspx) and [House of Representatives](http://www.congress.gov.ph/legisdocs/?v=bills) websites, normalized, on demand.

This is a checklist for the project's major tickets. Implement the following:

- [x] Fetching Senate bills
- [x] Fetching Senators
- [x] Fetch one senate bill
- [x] Fetch House of Representative Bills
- [ ] Fetch Congressmen
- [ ] Fetch one congress bill
- [ ] Search by bill
- [ ] Collect and analyze the _text_ used for labeling the status of a bill
- [ ] Implement bill data merging and normalization
- [ ] Produce mobile UI mockups
- [ ] Implement UI

**Comment by devcsrj** [comment]
As it turns out, a lot of pre-processing needs to be done before I can create a usable backend for mobile. All backend work is now introduced as a separate project - https://github.com/devcsrj/klerk
